version: "3.8"

services:
  dank-db:
    image: "mariadb:10.8"
    container_name: "dank-db"
    restart: "always"
    environment:
      MARIADB_ROOT_PASSWORD: "previetcomrade"
      MARIADB_DATABASE: "dankabase"
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    networks:
      - danknetwork

  yt-dl:
    container_name: "yt-dl"
    build:
      context: ./ytdl
    image: "ytdl"
    restart: "always"
    ports:
      - "4321:8000"
    env_file:
      - .env.docker
    volumes:
      - dankuploads-dir:/app/_serve
    depends_on:
      - dank-db
    networks:
      - danknetwork

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_serve/
  db-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_db/etc/
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_db/var/

networks:
  danknetwork: {}
