version: "3.8"

services:
  dank-db:
    image: "mariadb:10.8"
    container_name: "dank-db"
    restart: "always"
    environment:
      MARIADB_ROOT_PASSWORD: "previetcomrade"
      MARIADB_DATABASE: "dankabase"
    ports:
      - 3307:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

  yt-scraper:
    container_name: "yt-scraper"
    image: "baraamasri/yt-scrape"
    restart: "always"
    ports:
      - "1234:8080"

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
  db-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_db/etc/
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_db/var/
