version: "3.8"

services:
  website:
    container_name: "dankmuzikk"
    build:
      context: .
    image: "dankmuzikk"
    restart: "always"
    ports:
      - "20250:8080"
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - ./google-service-account.json:/app/google-service-account.json
