services:
  server:
    container_name: "dankmuzikk-server"
    build:
      context: ./server
    restart: "always"
    ports:
      - "20250:3000"
    stdin_open: true
    env_file:
      - .env.docker
    networks:
      - danknetwork
    depends_on:
      - dank-cdn
      - dank-ytdl

  dank-cdn:
    container_name: "dank-cdn"
    build:
      context: ./server
      dockerfile: Dockerfile.cdn
    restart: "always"
    ports:
      - "20251:3001"
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - dankuploads-dir:/app/.serve
    networks:
      - danknetwork
    depends_on:
      - dank-db

  dank-ytdl:
    container_name: "dank-ytdl"
    build:
      context: ./ytdl
    restart: "always"
    ports:
      - "4321:8000"
    env_file:
      - .env.docker
    volumes:
      - dankuploads-dir:/app/.serve
    depends_on:
      - dank-db
    networks:
      - danknetwork

networks:
  danknetwork:
    external: true

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.serve/
