version: "3.8"

services:
  dank-db:
    image: "mariadb:10.8"
    container_name: "dank-db"
    restart: "always"
    environment:
      MARIADB_ROOT_PASSWORD: "previetcomrade"
      MARIADB_DATABASE: "dankabase"
    ports:
      - 3307:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

  yt-scraper:
    container_name: "yt-scraper"
    image: "baraamasri/yt-scrape"
    restart: "always"
    ports:
      - "1234:8080"

  yt-dl:
    container_name: "yt-dl"
    build:
      context: ./ytdl
    image: "ytdl"
    restart: "always"
    ports:
      - "4321:8000"
    env_file:
      - .env.docker
    volumes:
      - dankuploads-dir:/app/_serve

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_serve/
  db-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_db/etc/
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_db/var/
