services:
  server-beta:
    container_name: "dankmuzikk-beta"
    build:
      dockerfile: ./Dockerfile
      context: ./app
    restart: "always"
    ports:
      - "20251:3000"
    stdin_open: true
    env_file:
      - .env.docker
    networks:
      - danknetwork

networks:
  danknetwork:
    external: true

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.serve/
