version: "3.8"

services:
  website:
    container_name: "dankmuzikk"
    build:
      context: .
    image: "dankmuzikk"
    restart: "always"
    ports:
      - "20250:3000"
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - ./google-service-account.json:/app/google-service-account.json
      - dankuploads-dir:/app/_serve
    networks:
      - danknetwork

  yt-scraper:
    container_name: "yt-scraper"
    image: "baraamasri/yt-scrape"
    restart: "always"
    ports:
      - "8080"
    networks:
      - danknetwork

networks:
  danknetwork: {}

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .
