services:
  server-beta:
    container_name: "dankmuzikk-beta"
    build:
      dockerfile: ./Dockerfile
      context: ./server
    restart: "always"
    ports:
      - "20360:3000"
    stdin_open: true
    env_file:
      - .env.docker
    networks:
      - danknetwork

  web-client-beta:
    container_name: "dankmuzikk-web-beta"
    build:
      context: ./web
    restart: "always"
    ports:
      - "20361:3000"
    stdin_open: true
    env_file:
      - .env.docker
    networks:
      - danknetwork
    depends_on:
      - server-beta

networks:
  danknetwork:
    external: true

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.serve/
