version: "3.8"

services:
  app-beta:
    container_name: "dankmuzikk-beta"
    build:
      dockerfile: "./Dockerfile.beta"
      context: .
    image: "dankmuzikk-app-beta"
    restart: "always"
    ports:
      - "20251:3000"
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - ./google-service-account.json:/app/google-service-account.json
      - dankuploads-dir:/app/_serve
    networks:
      - danknetwork

networks:
  danknetwork:
    external: true

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_serve/
