version: "3.8"

services:
  app:
    container_name: "dankmuzikk"
    build:
      context: ./app
    image: "dankmuzikk-app"
    restart: "always"
    ports:
      - "20250:3000"
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - ./google-service-account.json:/app/google-service-account.json
      - dankuploads-dir:/app/_serve
    networks:
      - danknetwork
    depends_on:
      - yt-scraper
      - yt-dl

  yt-scraper:
    container_name: "yt-scraper"
    build:
      context: ./ytscraper
    image: "yt-scraper"
    restart: "always"
    ports:
      - 8080
    networks:
      - danknetwork

  yt-dl:
    container_name: "ytdl"
    build:
      context: ./ytdl
    image: "ytdl"
    restart: "always"
    ports:
      - 8000
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - dankuploads-dir:/app/_serve
    networks:
      - danknetwork

networks:
  danknetwork:
    external: true

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./_serve/
