services:
  server:
    container_name: "dankmuzikk-server"
    build:
      context: ./server
    restart: "always"
    ports:
      - "20250:3000"
    stdin_open: true
    env_file:
      - .env.docker
    networks:
      - danknetwork
    depends_on:
      - dank-db
      - dank-ytdl
      - dank-cdn

  web-client:
    container_name: "dankmuzikk-web"
    build:
      context: ./web
    restart: "always"
    ports:
      - "20252:3000"
    stdin_open: true
    env_file:
      - .env.docker
    networks:
      - danknetwork
    depends_on:
      - server

  dank-db:
    image: "mariadb:10.8"
    container_name: "dank-db"
    restart: "always"
    environment:
      MARIADB_ROOT_PASSWORD: "previetcomrade"
      MARIADB_DATABASE: "dankabase"
    ports:
      - 3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
    networks:
      - danknetwork

  dank-cdn:
    container_name: "dank-cdn"
    build:
      context: ./server
      dockerfile: Dockerfile.cdn
    restart: "always"
    ports:
      - "20251:3001"
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - dankuploads-dir:/app/.serve
    networks:
      - danknetwork
    depends_on:
      - dank-db

  dank-ytdl:
    container_name: "dank-ytdl"
    build:
      context: ./ytdl
    restart: "always"
    ports:
      - "4321:8000"
    env_file:
      - .env.docker
    volumes:
      - dankuploads-dir:/app/.serve
    depends_on:
      - dank-db
    networks:
      - danknetwork

networks:
  danknetwork: {}

volumes:
  dankuploads-dir:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.serve/
  db-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.db/etc/
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.db/var/
