version: "3.8"

services:
  website:
    container_name: "gdsc_cptools"
    build:
      context: .
    image: "gdsc_cptools"
    restart: "always"
    ports:
      - "20248:8080"
    stdin_open: true
    env_file:
      - .env.docker
    volumes:
      - gdsc_cptools-files:/tmp

volumes:
  gdsc_cptools-files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: .
