root = "."

[build]
bin = "./dankmuzikk serve"
cmd = "go generate && go build"
delay = 100
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  "_db",
  "_serve",
  "node_modules",
  "ytscraper",
  "ytdl",
]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "js", "css"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
