FROM golang:1.24-alpine AS build

WORKDIR /app
COPY . .

RUN apk add --no-cache make &&\
    make build-cdn

FROM alpine:latest AS run

WORKDIR /app
COPY --from=build /app/dankmuzikk-cdn ./dankmuzikk-cdn

EXPOSE 8080

CMD ["./dankmuzikk-cdn"]
