FROM golang:1.24-alpine AS build

WORKDIR /app
COPY . .

RUN apk add --no-cache make

RUN make build-eventhub

FROM alpine:latest AS run

WORKDIR /app
COPY --from=build /app/dankmuzikk-eventhub ./dankmuzikk-eventhub

EXPOSE 3002

CMD ["./dankmuzikk-eventhub"]
