name: Deployment

concurrency: beta

on:
  push:
    branches:
      - beta
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - non-existent
    paths-ignore:
      - "**.md"

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: beta
    steps:
      - name: rex-7567-e27
        uses: mbaraa/rex-action@v1.6.4
        with:
          server-url: ${{ secrets.REX_SERVER }}
          token: ${{ secrets.REX_KEY }}
          repo-name: dankmuzikk-beta
          commit-sha: ${{ github.sha }}
          latest-tag: ${{ github.ref }}
          compose-file-name: "docker-compose-beta.yml"
