// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package player

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func PlayerSticky(isMobile bool) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"muzikk\" class=\"hidden\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isMobile {
			templ_7745c5c3_Err = mobilePlayer().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = desktopPlayer().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div class=\"hidden\"><img class=\"w-[50px]\" src=\"/static/images/play-disabled-icon.svg\" alt=\"Play\"> <img class=\"w-[50px]\" src=\"/static/images/play-icon.svg\" alt=\"Play\"> <img class=\"w-[50px]\" src=\"/static/images/pause-disabled-icon.svg\" alt=\"Pause\"> <img class=\"w-[50px]\" src=\"/static/images/pause-icon.svg\" alt=\"Pause\"> <img class=\"w-[40px]\" src=\"/static/images/loop-icon.svg\" alt=\"Loop\"> <img class=\"w-[40px]\" src=\"/static/images/loop-once-icon.svg\" alt=\"Loop Once\"> <img class=\"w-[40px]\" src=\"/static/images/loop-off-icon.svg\" alt=\"Loop Off\"> <img class=\"w-[40px]\" src=\"/static/images/shuffle-icon.svg\" alt=\"Shuffle\"> <audio id=\"audio-player\" controls preload=\"none\"></audio></div><script src=\"/static/js/player.js\" lang=\"javascript\">\n    </script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
