root = "."

[build]
full_bin = "export `cat ../.env | xargs` && ./dankmuzikk-web"
cmd = "make generate build"
delay = 25
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  ".db",
  ".serve",
  "node_modules",
  "ytscraper",
  "ytdl",
]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "js", "css", "hs", "_hs"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
